namespace Parser.Models
{
    public class Service
    {
        public int _19 { get; set; }
        public int _256 { get; set; }
        public int _285 { get; set; }
        public int _248 { get; set; }
        public int _267 { get; set; }
        public int _97 { get; set; }
        public int _1 { get; set; }
        public int _64 { get; set; }
        public int _108 { get; set; }
        public int _29 { get; set; }
        public int _272 { get; set; }
        public int _49 { get; set; }
        public int _31 { get; set; }
        public int _140 { get; set; }
        public int _25 { get; set; }
        public int _253 { get; set; }
        public int _273 { get; set; }
        public int _100 { get; set; }
        public int _28 { get; set; }
        public int _161 { get; set; }
        public int _130 { get; set; }
        public int _283 { get; set; }
        public int _8 { get; set; }
        public int _24 { get; set; }
        public int _23 { get; set; }
        public int _220 { get; set; }
        public int _268 { get; set; }
        public int _57 { get; set; }
        public int _4 { get; set; }
        public int _111 { get; set; }
        public int _14 { get; set; }
        public int _15 { get; set; }
        public int _12 { get; set; }
        public int _5 { get; set; }
        public int _96 { get; set; }
        public int _11 { get; set; }
        public int _183 { get; set; }
        public int _142 { get; set; }
        public int _2 { get; set; }
        public int _84 { get; set; }
        public int _186 { get; set; }
        public int _246 { get; set; }
        public int _255 { get; set; }
        public int _544 { get; set; }
        public int _286 { get; set; }
        public int _21 { get; set; }
        public int _247 { get; set; }
        public int _238 { get; set; }
        public int _284 { get; set; }
        public int _178 { get; set; }
        public int _35 { get; set; }
        public int _167 { get; set; }
        public int _244 { get; set; }
        public int _239 { get; set; }
        public int _166 { get; set; }
        public int _120 { get; set; }
        public int _149 { get; set; }
        public int _34 { get; set; }
        public int _282 { get; set; }
        public int _110 { get; set; }
        public int _109 { get; set; }
        public int _237 { get; set; }
        public int _115 { get; set; }
        public int _141 { get; set; }
        public int _39 { get; set; }
        public int _553 { get; set; }
        public int _287 { get; set; }
        public int _91 { get; set; }
        public int _259 { get; set; }
        public int _32 { get; set; }
        public int _242 { get; set; }
        public int _27 { get; set; }
        public int _264 { get; set; }
        public int _250 { get; set; }
        public int _153 { get; set; }
        public int _266 { get; set; }
        public int _105 { get; set; }
        public int _262 { get; set; }
        public int _258 { get; set; }
        public int _152 { get; set; }
        public int _159 { get; set; }
        public int _103 { get; set; }
        public int _127 { get; set; }
        public int _36 { get; set; }
        public int _131 { get; set; }
        public int _22 { get; set; }
        public int _71 { get; set; }
        public int _30 { get; set; }
        public int _10 { get; set; }
        public int _3 { get; set; }
        public int _6 { get; set; }
        public int _40 { get; set; }
        public int _37 { get; set; }
        public int _7 { get; set; }
        public int _139 { get; set; }
        public int _102 { get; set; }
        public int _76 { get; set; }
        public int _80 { get; set; }
        public int _73 { get; set; }
        public int _72 { get; set; }
        public int _145 { get; set; }
        public int _165 { get; set; }
        public int _249 { get; set; }
        public int _70 { get; set; }
        public int _74 { get; set; }
        public int _119 { get; set; }
        public int _162 { get; set; }
        public int _174 { get; set; }
        public int _113 { get; set; }
        public int _60 { get; set; }
        public int _58 { get; set; }
        public int _33 { get; set; }
        public int _26 { get; set; }
        public int _9 { get; set; }
        public int _38 { get; set; }
        public int _136 { get; set; }
        public int _128 { get; set; }
        public int _154 { get; set; }
        public int _123 { get; set; }
        public int _150 { get; set; }
        public int _254 { get; set; }
        public int _261 { get; set; }
        public int _209 { get; set; }
        public int _180 { get; set; }
        public int _151 { get; set; }
        public int _116 { get; set; }
        public int _81 { get; set; }
        public int _206 { get; set; }
        public int _169 { get; set; }
        public int _234 { get; set; }
        public int _168 { get; set; }
        public int _243 { get; set; }
        public int _172 { get; set; }
        public int _176 { get; set; }
        public int _56 { get; set; }
        public int _173 { get; set; }
        public int _170 { get; set; }
        public int _156 { get; set; }
        public int _271 { get; set; }
        public int _555 { get; set; }
        public int _288 { get; set; }
        public int _155 { get; set; }
        public int _148 { get; set; }
        public int _107 { get; set; }
        public int _269 { get; set; }
        public int _122 { get; set; }
        public int _129 { get; set; }
        public int _160 { get; set; }
        public int _101 { get; set; }
        public int _112 { get; set; }
        public int _53 { get; set; }
        public int _245 { get; set; }
        public int _202 { get; set; }
        public int _204 { get; set; }
        public int _82 { get; set; }
        public int _114 { get; set; }
        public int _61 { get; set; }
        public int _66 { get; set; }
        public int _212 { get; set; }
        public int _213 { get; set; }
        public int _125 { get; set; }
        public int _163 { get; set; }
        public int _88 { get; set; }
        public int _41 { get; set; }
        public int _251 { get; set; }
        public int _63 { get; set; }
        public int _280 { get; set; }
        public int _43 { get; set; }
        public int _42 { get; set; }
        public int _13 { get; set; }
        public int _59 { get; set; }
        public int _279 { get; set; }
        public int _215 { get; set; }
        public int _292 { get; set; }
        public int _143 { get; set; }
        public int _257 { get; set; }
        public int _94 { get; set; }
        public int _69 { get; set; }
        public int _203 { get; set; }
        public int _289 { get; set; }
        public int _93 { get; set; }
        public int _208 { get; set; }
        public int _179 { get; set; }
        public int _210 { get; set; }
        public int _211 { get; set; }
        public int _55 { get; set; }
        public int _90 { get; set; }
        public int _44 { get; set; }
        public int _207 { get; set; }
        public int _260 { get; set; }
        public int _118 { get; set; }
        public int _281 { get; set; }
        public int _278 { get; set; }
        public int _135 { get; set; }
        public int _75 { get; set; }
        public int _221 { get; set; }
        public int _192 { get; set; }
        public int _52 { get; set; }
        public int _547 { get; set; }
        public int _226 { get; set; }
        public int _175 { get; set; }
        public int _65 { get; set; }
        public int _106 { get; set; }
        public int _171 { get; set; }
        public int _48 { get; set; }
        public int _98 { get; set; }
        public int _46 { get; set; }
        public int _144 { get; set; }
        public int _126 { get; set; }
        public int _252 { get; set; }
        public int _236 { get; set; }
        public int _188 { get; set; }
        public int _50 { get; set; }
        public int _147 { get; set; }
        public int _121 { get; set; }
        public int _195 { get; set; }
        public int _200 { get; set; }
        public int _241 { get; set; }
        public int _556 { get; set; }
        public int _177 { get; set; }
        public int _133 { get; set; }
        public int _164 { get; set; }
        public int _20 { get; set; }
        public int _265 { get; set; }
        public int _104 { get; set; }
        public int _138 { get; set; }
        public int _77 { get; set; }
        public int _78 { get; set; }
        public int _277 { get; set; }
        public int _158 { get; set; }
        public int _47 { get; set; }
        public int _276 { get; set; }
        public int _132 { get; set; }
        public int _62 { get; set; }
        public int _196 { get; set; }
    }
}